### ISSUE TITLE
TSTL 'self' is not being translated to 'this' when using source mapping.

### ISSUE THREAD

**Issue by Straskal** [tomblind/local-lua-debugger-vscode#24]
Hi there! Thanks for the amazing extension.

I'm running into a debugging issue when using source mapping for TSTL. It appears that the 'self' variable is not being translated to 'this'. So I cannot inspect 'this' or fields on 'this' because this is `nil`.

An inconvenient work-around. If i just store my fields in local variables, I am able to inspect them.

```ts
// Unable to inspect 'this' or 'this._thing'.
// I am able to inspect 'localThing' once I've let the line execute.
const localThing = this._thing;
```

**Comment by tomblind** [comment]
This isn't supported by the debugger right now, but I'm not sure TSTL even provides that info in its source maps. I'll investigate what will be involved in getting this to work.

You should be able to put 'self' in the watch window to inspect this (so you don't have to modify code).

**Comment by Straskal** [comment]
Cool beans. Thanks!

**Comment by tomblind** [comment]
Currently, TSTL source maps handle renamed variables, but don't handle the mapping of `self` to `this` (TypeScriptToLua/TypeScriptToLua#899). I believe this should be easy to implement, though.

But, adding support for this to the debugger may be tricky. Since TS variable names can contain a lot of characters that are invalid in lua, I can't just do some metatable magic to map the names. Evaluated code like when you hover the mouse or use the watch window would have to be manually parsed. I may go with a partial solution for now that handles simple cases where the evaluated code is just a single identifier.

**Comment by Straskal** [comment]
Thank you for getting the issue onto the TSTL board. 

The partial solution sounds good. Handling `$vars`, etc.. would be an interesting problem to solve for. But single identifiers are the way to go.

**Comment by tomblind** [comment]
I was mistaken about TSTL not supporting the name mapping (see that ticket for info).

I just pushed a release that has 'experimental' support for this. It should work for common cases, but can probably be broken by putting less trivial expressions in the watch window.

**Comment by Straskal** [comment]
Tested it out this morning and it's working wonderfully. Thank you , sir.

**Comment by tomblind** [comment]
Good to hear. By the way, it should work in conditional breakpoints as well.
