### ISSUE TITLE
Nice work! i like it. Unimportant a few things..

### ISSUE THREAD

**Issue by mumin16** [tomblind/local-lua-debugger-vscode#3]
1- Globals's window is jam-packed with Lua's own globals so i can't find my own globals. can you seperatly capsulate them?
2- can you magic for escape from require("lldebugger").start() line?
3-if we make step on last line, we're falling inside lldebuuger.lua. here, the debugging must be end...

**Comment by tomblind** [comment]
Thanks for the feedback!

> 1- Globals's window is jam-packed with Lua's own globals so i can't find my own globals. can you seperatly capsulate them?

I don't believe there's a way to distinguish which globals are Lua's and which are made by users. Lua treats them all the same. For example, you can assign your own values to Lua's: `string = {}`

> 2- can you magic for escape from require("lldebugger").start() line?

I'm not quite sure what you mean by a magic escape. If you are using a custom environment, the debugger needs to be launched by seomthing in the user's code, since it can't be 'injected' on the command line.

> 3-if we make step on last line, we're falling inside lldebuuger.lua. here, the debugging must be end...

I'll make a separate issue for this.
